# Config file for automatic testing at travis-ci.org
sudo: required

language: python

python:
    - 2.7

services:
    - docker

before_install:
    - docker build -t hydroearth/hydro-model-generator-wflow .
    - docker run hydroearth/hydro-model-generator-wflow

install:
    - pip install -U tox-travis

deploy:
    provider: script
    script: bash docker_push
    on:
        branch: master

## Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors

#
## Command to run tests, e.g. python setup.py test
#script: tox
#
## Assuming you have installed the travis-ci CLI tool, after you
## create the Github repo and add it to Travis, run the
## following command to finish PyPI deployment setup:
## $ travis encrypt --add deploy.password
#deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  user: rogersckw9
#  password:
#    secure: PLEASE_REPLACE_ME
#  on:
#    tags: true
#    repo: ckrogers/hydro_model_generator_wflow
#    python: 3.6
