sudo: required
language: python
python:
- 3.6
services:
- docker
env:
  global:
  - secure:
before_install:
- openssl aes-256-cbc -K $encrypted_e5adff6c0905_key -iv $encrypted_e5adff6c0905_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- mkdir -p lib
- docker build -t eu.gcr.io/hydro-model-generator-wflow/wflow .
install:
- pip install -U tox-travis
script:
- tox
deploy:
- provider: script
  script: bash docker_push
  on:
    branch: Docker-implementation
- provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: hydro-model-generator-wflow
  verbosity: debug
  default: true
  on:
    branch: Docker-implementation
