service: hydro-model-generator-wflow

runtime: custom
env: flex
entrypoint: psqworker hydroearth.tasks.worker.models_queue

runtime_config:
  python_version: 3

health_check:
  enable_health_check: False

automatic_scaling:
  max_num_instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

#handlers:
#- url: .*
#  script: main.app
